import typescript from "rollup-plugin-typescript2";

import pkg from "./package.json";

export default {
  input: "src/index.tsx",
  output: [
    {
      file: pkg.main,
      format: "cjs",
      exports: "named",
      sourcemap: true,
      strict: false,
    },
  ],
  plugins: [typescript()],
  external: [
    "@crud-studio/react-crud-core",
    "@ebay/nice-modal-react",
    "@emotion/react",
    "@emotion/styled",
    "@lottiefiles/react-lottie-player",
    "@mui/icons-material",
    "@mui/lab",
    "@mui/material",
    "@mui/material/styles",
    "@mui/system",
    "body-scroll-lock",
    "copy-to-clipboard",
    "events",
    "lodash",
    "mousetrap",
    "notistack",
    "react",
    "react-dom",
    "react-dropzone",
    "react-hook-form",
    "react-intl",
    "react-joyride",
    "react-merge-refs",
    "react-pdf",
    "react-router-dom",
    "react-use",
    "react-virtualized-auto-sizer",
    "react-window",
    "type-fest",
    "uuid",
    "xlsx",
  ],
};
